stages:
  data_collection:
    cmd: python src/data_collection.py
    deps:
    - src/data_collection.py
    params:
    - data_collection.test_size
    outs:
    - data/raw
  data_prep:
    cmd: python src/data_prep.py
    deps:
    - data/raw
    - src/data_prep.py
    outs:
    - data/processed
  model_building:
    cmd: python model/model_building.py
    deps:
    - data/processed
    - model/model_building.py
    params:
    - model_building.n_estimators
    outs:
    - models/model.pkl
  model_eval:
    cmd: python model/model_eval.py
    deps:
    - models/model.pkl
    - model/model_eval.py
    outs:
    - reports/run_info.json
  model_registration:
    cmd: python model/model_reg.py
    deps:
    - model/model_reg.py
    - reports/run_info.json
